//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Mirage Editor.rc
//
#define IDR_SAMPLES                     4
#define IDD_PROGRESS                    5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_WAV_NOT_MONO                101
#define IDP_FAILED_TO_CREATE            102
#define IDS_CANNOT_LOAD_WAV             103
#define IDS_CANNOT_SAVE_WAV             104
#define IDD_MESSAGES                    104
#define IDS_UPDATE_AVAILABLE            105
#define IDD_PREFERENCES                 106
#define IDS_UPDATE_NO                   106
#define IDS_UPDATE_NOCHECK              107
#define IDR_HTML_RESYNTHESIZE           108
#define IDR_HTML_MIRPROGRAM             109
#define IDR_MAINFRAME                   128
#define IDR_MirageSampDumpTYPE          129
#define IDD_RECEIVE_SAMPLES             129
#define IDD_SEND_SAMPLES                130
#define IDR_DiskImageType               130
#define IDD_RESAMPLE                    139
#define IDD_LOOPDIALOG                  141
#define IDB_LOOPSTART                   143
#define IDB_LOOPEND                     144
#define IDD_KEYMAPPER                   144
#define IDD_MULTIPLE_COPIES             145
#define IDD_BANK_SELECT                 146
#define IDS_UPDATE                      147
#define IDD_RESYNTHESIS                 148
#define IDD_PROGRAM_SETTINGS            150
#define IDC_COMBO_MIDI_INPORT           1001
#define IDC_CONVERTER                   1007
#define IDC_LIST_LOWER                  1011
#define IDC_LIST_UPPER                  1012
#define IDC_RECEIVE_SAMPLES             1013
#define IDC_RECEIVE_ABORT               1014
#define IDC_MONOMODE                    1015
#define IDC_LFO_FREQ                    1018
#define IDC_LFO_FREQ_SLID               1018
#define IDC_LFO_DEPTH                   1019
#define IDC_FILTER_CUTOFF               1020
#define IDC_FILTER_RESONANCE            1021
#define IDC_FILTER_KEYB_TRACK           1024
#define IDC_PROGRESS                    1029
#define IDC_DO_RESAMPLING               1034
#define IDC_STEREO2MONO                 1035
#define IDC_RESAMPLE_PRELISTEN          1036
#define IDC_IMAGE                       1037
#define IDC_END_F                       1039
#define IDC_END_FINE_F                  1040
#define IDC_END_FINE_B                  1041
#define IDC_END_B                       1042
#define IDC_START_F                     1043
#define IDC_PAGE_RESET                  1044
#define IDC_FORWARD_BACKWARD_LOOP       1045
#define IDC_START_B                     1046
#define IDC_TRANSMIT_SAMPLES            1047
#define IDC_TRANSMIT_ABORT              1048
#define IDC_LOOP_TOGGLE                 1050
#define IDC_PAGES_COMBO                 1051
#define IDC_STATIC_PAGES                1052
#define IDC_ORIGINAL_KEY                1053
#define IDC_MESSAGE                     1054
#define IDC_MIDI_KEYS                   1056
#define IDC_LOWER1_MAP                  1057
#define IDC_LOWER2_MAP                  1058
#define IDC_DLG_PLAY_LOOP               1058
#define IDC_LOWER3_MAP                  1059
#define IDC_LOWER4_MAP                  1060
#define IDC_REPEAT_SPIN                 1060
#define IDC_LOWER5_MAP                  1061
#define IDC_LOWER6_MAP                  1062
#define IDC_REPEATCOUNT                 1062
#define IDC_LOWER7_MAP                  1063
#define IDC_LOWER8_MAP                  1064
#define IDC_BANK1                       1064
#define IDC_UPPER1_MAP                  1065
#define IDC_BANK2                       1065
#define IDC_UPPER2_MAP                  1066
#define IDC_BANK3                       1066
#define IDC_UPPER3_MAP                  1067
#define IDC_BANK4                       1067
#define IDC_UPPER4_MAP                  1068
#define IDC_BANK5                       1068
#define IDC_UPPER5_MAP                  1069
#define IDC_BANK6                       1069
#define IDC_UPPER6_MAP                  1070
#define IDC_UPPER7_MAP                  1071
#define IDC_EDIT1                       1071
#define IDC_LFO_FREQ_EDIT               1071
#define IDC_UPPER8_MAP                  1072
#define IDC_CHECK_UPDATES               1072
#define IDC_DSP_SINE                    1073
#define IDC_DSP_NOISE                   1074
#define IDC_DSP_LINEAR                  1075
#define IDC_SPIN_MAXFREQ                1077
#define IDC_DSP_MAXFREQ                 1083
#define IDC_DSP_BANDSPEROCTAVE          1085
#define IDC_SPIN_BANDSPEROCTAVE         1086
#define IDC_DSP_PIXPERSEC               1087
#define IDC_SPIN_PIXPERSEC              1088
#define IDC_FILTER_ENV_ATTACK           1091
#define IDC_FILTER_ENV_PEAK             1092
#define IDC_FILTER_ENV_DECAY            1093
#define IDC_FILTER_ENV_SUSTAIN          1094
#define IDC_FILTER_ENV_RELEASE          1095
#define IDC_LFO_DEPTH_EDIT              1096
#define IDC_CUTOFF_EDIT                 1097
#define IDC_RESO_EDIT                   1098
#define IDC_SLIDER1                     1099
#define IDC_FILT_ATT_EDIT               1099
#define IDC_COMBO_MIDI_OUTPORT          1100
#define IDC_FILT_PEAK_EDIT              1100
#define IDC_COMBO_AUDIO_OUT             1101
#define IDC_FILT_DECAY_EDIT             1101
#define IDC_FILT_SUS_EDIT               1102
#define IDC_FILT_REL_EDIT               1103
#define IDC_AMP_ENV_ATTACK              1104
#define IDC_AMP_ENV_PEAK                1105
#define IDC_AMP_ENV_DECAY               1106
#define IDC_AMP_ENV_SUSTAIN             1107
#define IDC_AMP_ENV_RELEASE             1108
#define IDC_AMP_ATT_EDIT                1109
#define IDC_AMP_PEAK_EDIT               1110
#define IDC_AMP_DECAY_EDIT              1111
#define IDC_AMP_SUS_EDIT                1112
#define IDC_AMP_REL_EDIT                1113
#define IDC_FILTER_ATT_MOD              1114
#define IDC_FILTER_PEAK_MOD             1115
#define IDC_FILTER_DEC_MOD              1116
#define IDC_FILTER_SUS_MOD              1117
#define IDC_FILTER_REL_MOD              1118
#define IDC_FILT_ATT_MOD_EDIT           1119
#define IDC_FILT_PEAK_MOD_EDIT          1120
#define IDC_FILT_DECAY_MOD_EDIT         1121
#define IDC_FILT_SUS_MOD_EDIT           1122
#define IDC_FILT_REL_MOD_EDIT           1123
#define IDC_AMP_ATT_MOD                 1124
#define IDC_AMP_PEAK_MOD                1125
#define IDC_AMP_DEC_MOD                 1126
#define IDC_AMP_SUS_MOD                 1127
#define IDC_AMP_REL_MOD                 1128
#define IDC_AMP_ATT_MOD_EDIT            1129
#define IDC_AMP_PEAK_MOD_EDIT           1130
#define IDC_AMP_DECAY_MOD_EDIT          1131
#define IDC_AMP_SUS_MOD_EDIT            1132
#define IDC_AMP_REL_EDIT2               1133
#define IDC_AMP_REL_MOD_EDIT            1133
#define ID_MESSAGE_PAGE                 1138
#define ID_MESSAGE_RATE                 1139
#define ID_MESSAGE_GENERAL              1140
#define ID_MESSAGE_PITCH                1141
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_MIRAGE_RECEIVESAMPLE         32771
#define ID_MIRAGE_SENDSAMPLE            32772
#define ID_MIRAGE_PREFERENCES           32773
#define ID_PLAYSND                      32774
#define ID_LOOP                         32775
#define ID_PLAY_AUDIO                   32778
#define ID_CLOSE_WINDOW                 32781
#define ID_TOOLS_LOOPWINDOW             32785
#define ID_TOOLS_REVERSESAMPLE          32786
#define ID_TOOLS_RESAMPLE               32787
#define ID_TOOLS_NORMALIZE              32788
#define ID_TOOLS_PITCHDETECT            32792
#define ID_DISPLAYTYPE_WAVEDRAW         32800
#define ID_DISPLAYTYPE_3DTYPEA          32801
#define ID_DISPLAYTYPE_3DTYPEB          32802
#define ID_DISPLAYTYPE_WAVEDRAW32807    32807
#define ID_DISPLAYTYPE_WAVEDRAW_OLD     32808
#define ID_EDIT_PASTESPECIAL            32809
#define ID_PASTESPECIAL_OVERWRITE       32810
#define ID_PASTESPECIAL_APPEND          32811
#define ID_PASTESPECIAL_PREPEND         32812
#define ID_PASTESPECIAL_MULTIPLECOPIES  32813
#define ID_PASTESPECIAL_MIX             32814
#define ID_MIRAGE_KEYMAPPING            32815
#define ID_MIRAGE_SENDLOOPPOINTS        32816
#define ID_EDIT_TRUNCATE                32825
#define ID_TRUNCATE_AFTERLOOP           32826
#define ID_TRUNCATE_BEFORELOOP          32827
#define ID_TRUNCATE_ONLYKEEPLOOP        32828
#define ID_TOOLS_FOURIERANALYSYS        32829
#define ID_TOOLS_RESYNTHESIZE           32830
#define ID_TOOLS_DETECTPITCH            32831
#define ID_TOOLS_ALLIGNTOPAGES          32832
#define ID_HELP_REPORTBUG               32840
#define ID_HELP_CHECKFORUPDATES         32841
#define ID_MIRAGE_PROGRAMSETTINGS       32844
#define ID_MIRAGE_SYSTEMPARAMETERS      32845

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32849
#define _APS_NEXT_CONTROL_VALUE         1100
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
